eventa:
  kafka:
    bootstrap-servers: localhost:9092
    trusted-packages:
    command-bus: BaseCommand
    event-bus: BaseEvent
  mongodb:
    username: username
    password: password
    port: 27017
    host: localhost
    database: events_store
    authentication-database: admin

spring:
  application:
    name: spring-boot-app
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-
      properties:
        enable-idempotence: true
        acks: all
        retries: 5
        max-in-flight-requests-per-connection: 5
    consumer:
      group-id: eventa-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: false
      max-poll-records: 500
      heartbeat-interval: 5000
      fetch-max-wait: 5000
    listener:
      missing-topics-fatal: false
      ack-mode: manual                    # Manual acknowledgment mode

  # Mongo DB
  data:
    mongodb:
      repositories:
        type: imperative
      authentication-database: admin
      auto-index-creation: true
      database: eventstore
      username: username
      password: password
      port: 27017
      host: localhost



